name: Auto-merge Codex PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_run:
    workflows: ['Shipyard CI']
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: >
      (github.event_name == 'pull_request' &&
       contains(join(github.event.pull_request.labels.*.name, ','), 'automerge'))
      || (github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.event == 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          commit-message: pull-request-title
          required-labels: automerge
          pull-request: ${{ github.event.pull_request.url || github.event.workflow_run.pull_requests[0].url }}
