name: Auto-merge labeled PRs
on:
  # Fires when your CI workflow finishes
  workflow_run:
    workflows: ['Shipyard CI']   # MUST match your CI workflow name EXACTLY
    types: [completed]
  # Also catch Vercel finishing (check suites)
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge:
    if: >
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success')
      ||
      (github.event_name == 'check_suite' &&
       github.event.check_suite.conclusion == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Resolve head SHA
        id: sha
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            echo "sha=${{ github.event.workflow_run.head_sha }}" >> "$GITHUB_OUTPUT"
          else
            echo "sha=${{ github.event.check_suite.head_sha }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Find PR by commit SHA
        id: find
        uses: peter-evans/find-pull-request@v3
        with:
          commit: ${{ steps.sha.outputs.sha }}

      - name: Auto-merge if labeled
        if: steps.find.outputs.pull_request_number != ''
        uses: peter-evans/auto-merge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.find.outputs.pull_request_number }}
          required-labels: automerge
          merge-method: squash
          commit-message: pull-request-title
