name: Shipyard CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: shipyard-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack + pnpm
        run: |
          set -euxo pipefail
          corepack enable
          corepack prepare pnpm@9 --activate
          node -v
          pnpm -v

      - name: Print package.json scripts (if present)
        run: |
          set -euxo pipefail
          if [ -f package.json ]; then
            node -e "const p=require('./package.json'); console.log('scripts:', p.scripts||{})"
          else
            echo "No package.json at repo root"
          fi

      - name: Install dependencies (frozen if lock present)
        run: |
          set -euxo pipefail
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            pnpm install
          fi

      - name: Typecheck (if script exists)
        run: |
          set -euxo pipefail
          node -e "process.exit(!((require('./package.json').scripts||{}).typecheck))" || { echo 'No typecheck script; skipping'; exit 0; }
          pnpm typecheck

      - name: Lint (if script exists)
        run: |
          set -euxo pipefail
          node -e "process.exit(!((require('./package.json').scripts||{}).lint))" || { echo 'No lint script; skipping'; exit 0; }
          pnpm lint

      - name: Test (if script exists)
        run: |
          set -euxo pipefail
          node -e "process.exit(!((require('./package.json').scripts||{}).test))" || { echo 'No test script; skipping'; exit 0; }
          pnpm test -- --reporter=dot

      - name: Build (if script exists)
        run: |
          set -euxo pipefail
          node -e "process.exit(!((require('./package.json').scripts||{}).build))" || { echo 'No build script; skipping'; exit 0; }
          pnpm build

      - name: Publish commit status (success)
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request ? context.payload.pull_request.head.sha : context.sha;
            await github.request('POST /repos/{owner}/{repo}/statuses/{sha}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'success',
              context: 'shipyard/ci',
              description: 'Shipyard CI passed',
              target_url: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            });

      - name: Publish commit status (failure)
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.pull_request ? context.payload.pull_request.head.sha : context.sha;
            await github.request('POST /repos/{owner}/{repo}/statuses/{sha}', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha,
              state: 'failure',
              context: 'shipyard/ci',
              description: 'Shipyard CI failed',
              target_url: `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            });
